# Generated by Django 5.2 on 2025-05-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='app.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ad_period_start', models.DateField()),
                ('ad_period_end', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('promotion_text', models.CharField(blank=True, max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='weekly_ads/')),
                ('description', models.TextField(blank=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ads', to='app.promoter')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ads', to='app.store')),
            ],
        ),
    ]
