# Generated by Django 5.2 on 2025-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyad',
            old_name='ad_period_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='weeklyad',
            old_name='ad_period_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weeklyad',
            name='promoter',
        ),
        migrations.AddField(
            model_name='promoter',
            name='stores_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyad',
            name='promotion_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='weeklyad',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
    ]
